---
# Service
apiVersion: v1
kind: Service
metadata:
  name: elk-kibana
  labels:
    component: elk-kibana
    role: kibana
spec:
  selector:
    component: elk-kibana
    role: kibana
  ports: 
  - name: kibana
    protocol: TCP
    port: 5601
    targetPort: 5601
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elk-kibana
  #namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /elk/kibana
        backend:
          serviceName: elk-kibana
          servicePort: 5601
---
# Deployment 
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elk-kibana
  labels:
    component: elk-kibana
    role: kibana
spec:
  replicas: 1
  selector:
    matchLabels:  
      component: elk-kibana
      role: kibana 
  template:
    metadata:
      labels:
        component: elk-kibana
        role: kibana 
    spec:
      containers:
      - name: elk-kibana
        image: docker.elastic.co/kibana/kibana:6.5.3
        env:
        - name: ELASTICSEARCH_URL
          value: http://elk-elasticsearch:9200 
        - name: SERVER_NAME
          value: kibana 
        - name: SERVER_BASEPATH
          value: /elk/kibana 
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP 

